### ISSUE TITLE
Jump to Tab

### ISSUE THREAD

**Issue by securitygeneration** [bytebutcher/burp-quicker-context#1]
Could something similar be done in order to jump to a particular tab? For example in Repeater when you have 20+ named tabs, but the stacked tab UI makes things impossible to find.

**Comment by bytebutcher** [comment]
Actually i have some code which does exactly that.
The extension let you choose a shortcut with which you can open a dialog containing a search field for tabs. Initially i wanted to include the quicker context in this dialog, too. However, i couldn't figure out how to retrieve the context menu entries without actually opening the context-menu.
In the end i just extracted the quicker context functionality into a separate extension and didn't publish the "quicker tabs" since i didn't think people would find much use in it.
However, i'm happy to publish. Just need to piece the code fragments together again. I'll keep you posted about the progress.

**Comment by bytebutcher** [comment]
I've pushed the latest changes of the Quicker-Tabs-Extension (see https://github.com/bytebutcher/burp-quicker-tabs) to github. This will add a new context menu entry called "Tabs" in which you can choose the tab you want to select.

Since the context menu entries are also available via the Quicker-Context Dialog you can select a tab using fuzzy search. 

Note, that this is just a draft. Maybe i will merge the Quicker-Context and Quicker-Tabs extension in the future.

**Comment by bytebutcher** [comment]
Ok, i've merged the code and also added the ability to open the "Quicker" dialog using a customizable keyboard shortcut (default = shift + space). When opening the dialog using the keyboard shortcut, it is only possible to select tabs, since i saw no way to retrieve the context menu entries.

![open-tab](https://user-images.githubusercontent.com/40742871/74593866-3c631480-5030-11ea-8b11-8e204f56d62b.png)
![enter-shortcut](https://user-images.githubusercontent.com/40742871/74593867-3d944180-5030-11ea-843f-6e21b167be27.png)
